#!/usr/bin/env bash

# colors variables

GREEN="\x1B[32m"
YELLOW="\x1B[33m"
YELLOW_BRIGHT="\x1B[93m"
BLUE="\x1B[34m"
CYAN="\x1B[36m"
RED="\x1B[31m"
WHITE="\x1B[37m"
BLACK="\e[0;30m"
BOLD="\x1B[1m"
RESET="\x1B[0m"

# help command

help() {
  echo -e "${BOLD}${GREEN}[!]${RESET} Welcome to ${BOLD}${CYAN}flags${RESET}! View all commands:"

  echo "Other Commands"
  echo "flags -h      Displays this menu."
  echo "flags -upd    Downloads the newest flags from the github repo."

  echo "Flag Commands"
  echo "flags -usa    Flag of USA."
  echo "flags -es     Flag of Spain."
  echo "flags -it     Flag of Italy."
  echo "flags -fr     Flag of France."
  echo "flags -pl     Flag of Poland."
  echo "flags -hu     Flag of Hungary."
  echo "flags -at     Flag of Austria."
  echo "flags -ru     Flag of Russia."
  echo "flags -bg     Flag of Bulgaria."
  echo "flags -ua     Flag of Ukraine."
  echo "flags -ff     Flag of Finland."
  echo "flags -dk     Flag of Denmark."
  echo "flags -se     Flag of Sweden."
  echo "flags -ch     Flag of Switzerland."
  echo "flags -ro     Flag of Romania."
  echo "flags -lv     Flag of Latvia."
  echo "flags -lt     Flag of Lithuania."
  echo "flags -cz     Flag of Czechia."
  echo "flags -gr     Flag of Greece."
  echo "flags -ie     Flag of Ireland."
  echo "flags -ee     Flag of Estonia."
  echo "flags -be     Flag of Belgium."
  echo "flags -de     Flag of Germany."
  echo "flags -tw     Flag of Taiwan."
}

# download flags data from the github repo. this allows more flags to be added without any work from the users

update() {
  if [ -f "$HOME/.local/share/flagdata.sh" ]; then
    rm "$HOME/.local/share/flagdata.sh"
  fi

  if [ ! -d "$HOME/.local/share/" ]; then
    mkdir -p "$HOME/.local/share/"
  fi

  curl -s "https://raw.githubusercontent.com/justleoo/flags/main/flagdata.sh" --output "$HOME/.local/share/flagdata.sh"
}

# check for flagdata and if not found run update() to download it

if [ ! -f "$HOME/.local/share/flagdata.sh" ]; then
  update
fi

source "$HOME/.local/share/flagdata.sh"

# cmds

for var in "$@"
do
  case $var in
    -h)
      help
      exit 0
    ;;
    -upd)
      echo -e "${BOLD}${CYAN}[!]${RESET} Updating flag list, please wait."
      update
      exit 0
    ;;
    -*)
      getflag "$var"
    ;;
  esac
done

echo -e "${BOLD}${GREEN}[!]${RESET} Hello! Welcome to ${BOLD}${CYAN}flags${RESET}, use ${BOLD}${CYAN}flags -h${RESET} to view all commands."
